### ISSUE TITLE
Why browser-sync instead of webpack-dev-server?

### ISSUE THREAD

**Issue by iyel** [AngularClass/NG6-starter#108]
Could you please explain?

**Comment by fesor** [comment]
browser sync has a lot of additional features (like browser synchronization, https out of the box and many other cool stuff), which speeds up development and testing your application (especially manual, since we can't fully automate UI testing without checking in by hands).

And since `webpack-dev-server` is just a simple express server with `webpack-dev-middleware`, why not use `webpack-dev-middleware` with browser sync? It gives us more power and doesn't brings much overhead.
